""" Program desenare triunghi, mediane si centrul de greutate """
from graphics import *
win = GraphWin("Desenare triunghi, mediane si centrul de greutate" ,500,500)
win.setCoords(0, 0, 500, 500)
message = Text(Point(100, 450), "Dati click pe trei puncte")
message.draw(win)
A = win.getMouse()
A.draw(win)
B = win.getMouse()
B.draw(win)
C = win.getMouse()
C.draw(win)
M = Line(B,C).getCenter()
N = Line(A,C).getCenter()
P = Line(A,B).getCenter()
G = Point((A.getX()+B.getX()+C.getX())/3.,(A.getY()+B.getY()+C.getY())/3.)
triunghi=Polygon(A,B,C)
MedAM = Line(A,M)
MedBN = Line(B,N)
MedCP = Line(C,P)
MedAM.setWidth(3)
MedBN.setWidth(3)
MedCP.setWidth(3)
MedAM.setOutline("red")
MedBN.setOutline("red")
MedCP.setOutline("red")
triunghi.setOutline("blue")
triunghi.setWidth(3)
triunghi.setWidth(3)
triunghi.draw(win)
MedAM.draw(win)
MedBN.draw(win)
MedCP.draw(win)
cercG = Circle(G,4)
cercG.setWidth(6)
cercG.setOutline("green")
cercG.draw(win)
AncorG = Point(G.getX()+20,G.getY())
TextG = Text(AncorG,"G")
TextG.draw(win)
win.getMouse()
win.close()
